name: prueba_maps
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.0
  google_maps_flutter: ^0.5.21
  permission_handler: ^4.2.0+hotfix.2
  http: ^0.12.0+4
  flutter_polyline_points: ^0.1.0
  cloud_firestore: ^0.13.3
  firebase_auth: ^0.15.5+2
  firebase_messaging: ^6.0.13
  shared_preferences: ^0.5.6+3
  animations: ^1.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo_artely.png"
  adaptive_icon_foreground: "assets/logo_artely.png"

flutter:
  assets:
  - assets/img/curved_arrow.png
  uses-material-design: true
